# Generated by Django 3.0 on 2022-01-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admindata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default=None, max_length=100)),
                ('Password', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'admindata',
            },
        ),
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=100)),
                ('AdsImage', models.ImageField(default=None, upload_to='static/Images')),
            ],
            options={
                'db_table': 'Advertisements',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.IntegerField(default=None)),
                ('Property_ID', models.IntegerField(default=None)),
                ('Area', models.CharField(default=None, max_length=100)),
                ('Price', models.CharField(default=None, max_length=100)),
                ('Date', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
        migrations.CreateModel(
            name='DigitalProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(default=None, max_length=100)),
                ('Link', models.CharField(default=None, max_length=500)),
                ('Image', models.ImageField(default=None, upload_to='static/Images')),
            ],
            options={
                'db_table': 'Digital Property',
            },
        ),
        migrations.CreateModel(
            name='Favaourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PropertyID', models.IntegerField(default=None)),
                ('UserID', models.IntegerField(default=None)),
                ('P_Type', models.CharField(default=None, max_length=100)),
                ('Sqft', models.IntegerField(default=None)),
                ('Area', models.CharField(default=None, max_length=100)),
                ('Price', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Favaourite',
            },
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(default=None, max_length=100)),
                ('Sqft', models.IntegerField(default=None)),
                ('PropertyType', models.CharField(default=None, max_length=100)),
                ('Area', models.CharField(default=None, max_length=100)),
                ('Address', models.CharField(default=None, max_length=100)),
                ('Landmark', models.CharField(default=None, max_length=100)),
                ('DeveloperName', models.CharField(default=None, max_length=100)),
                ('Price', models.CharField(default=None, max_length=100)),
                ('Bedroom', models.IntegerField(default=None)),
                ('Bathroom', models.IntegerField(default=None)),
                ('Furnished', models.CharField(default=None, max_length=100)),
                ('Parking', models.CharField(default=None, max_length=100)),
                ('CCTV', models.CharField(default=None, max_length=100)),
                ('Image', models.ImageField(default=None, upload_to='static/Images')),
            ],
            options={
                'db_table': 'PropertyDetails',
            },
        ),
        migrations.CreateModel(
            name='UserRegisters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=100)),
                ('Address', models.CharField(default=None, max_length=100)),
                ('Mobile', models.CharField(default=None, max_length=100)),
                ('Email', models.CharField(default=None, max_length=100)),
                ('Username', models.CharField(default=None, max_length=100)),
                ('Password', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'UserRegisters',
            },
        ),
    ]
